server: "&aAlein-MudarDps"
motd: "&a&lAlien&c&lPvP &6&l - &7&l&o Veja ja treinar sua habilidades aqui!"
siteVipI: "&aAdicionar a config depois"
siteVipII: "&aAdicionar a config depois"
siteVipIII: "&aAdicionar a config depois"
